version: '3'

services:
  registry:
    image: registry:2
    restart: unless-stopped
    ports:
    - "5000:5000"
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY="./data"
      - REGISTRY_AUTH="htpasswd"
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH="./auth/htpasswd"
      - REGISTRY_STORAGE_DELETE_ENABLED=True
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
  ui:
    image: joxit/docker-registry-ui:latest
    restart: unless-stopped
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=My Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
    ports:
      - 5001:80
    depends_on:
      - registry
